var quotes = ["Truth is the offstrping of silence and meditation. - Issac Newton", "As long as they know why they do it, the rest will follow. - Yoon Sean-hak",
"If you\'re 40 years old and the last book you read was from high school, you got a lot of catching up to do. - Villanueva", "You can teach competence.  You can\'t teach character. - Villanueva", "If you want to be a mathametician, you don\'t spend most of your time hanging out with writers. - Villanueva", "How to stay awake when you\'re reading...easy, stop reading and start doing something with the reading. - Mark Meyers",
"It\s not the destination.  It\s the journey. - Ralph Waldo Emerson", "I will prepare and some day my chance will come. - Abraham Lincoln", "Punch fear in the face. - Jon Acuff", "No one aims for average. - Jon Acuff",
"Action always beats intention.  Anyone can dream.  It\'s doing that is such a hasle. - Jon Acuff", "What\'s ordinary to one person can be extraordinary to another. - Seo Dal-mi", "Think about it: have YOU done anything impressive today? Your personal genius is right at your fingertips. Feel free to use it. - John MacCormich",
"If you wait for perfect conditions to seize an opportunity, you\'ll be wating till the day you die. - Mark Batterson", "Reading books is like lifting weights for the body. - John Villanueva", "If you want to succeed, you have to take control of your life. You have to influence yourself. - John Villanueva", "We need to focus our energies to be good at anything. - John Villanueva", "You must master a new way to think before you can master a new way to be.", "There is no chance, no destiny, no fate, that can circumvent or hinder or control the firm resolve of a determined soul. - Ella Wheeler Wilcox", "There\'s still some dreams floating around out there.  It\'s not too late, you just have to reach out and grab them. - Nick Campbell", "You have the courage to dream. Inspite of your limitations, you never give up on that dream. - Mr. Chetty", "Lift your head up. Take a breath. there\'s a lot of great possibilities out there. - Bill McMahon", "If you fight for your limitatons, you get to keep them. - Bill McMahon", 
"Take 100% responsibility, put in the work, read twice as much as you watch TV. Your life won't change until you do.", "Whatever it is you\'re scared of doing, DO IT. - Neil Gaiman.", "Continuous effort is the key to unlocking your potential.", "No man ever steps in the same river twice, for it is not the same river and he is not the same man. - Heraclitus", "If you think you\'re leading but no one is following, then you are only taking a walk. - John C. Maxwell", "Every person has the ability to improve in leadership.  Becoming a leader isn't a mystical subject. It can be appoarched very practically. - John C. Maxwell", "Leadership isn\'t about the title or having an office. It\'s about influence and the fact that you can make an impact on others. - John C. Maxwell", "If you want to grow as a leader, be prepared to be uncomfortable. - John C. Maxwell", "There is no progress without risk. - John C. Maxwell",
            "It\'s not the load that breaks you down.  It\'s the way you carry it. We are capable of carrying heavy things. - Jason Van Camp", "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill", "The desert would cover the entire world if it was sunny every day. We need the rain and the snow for plants and delicious fruits to grow. - Seo Dal-mi", "If the start is easy, then it\'ll be taken away easily as well. - Seo In-jin", "Luck favors the prepared.", "Stop trying to change everyone else, focus on finding your purpose and then elevate! - Jason Van Camp", "He that is good at making excuses is seldom good at anything else. - Benjamin Franklin", "You build on failure. You use it as a stepping stone. - Johnny Cash", "If you stay in your comfort zone, that is where you will fail. Success is not a comfortable procedure. - Steve Harvey", "You can\'t cheat the grind. - Nashaly Maldonado", "The world breaks everyone, many are strong at the broken places. - Ernest Hemingway.", 
              "It\'s not the load that breaks you down. It\'s the way you carry it. We are capable of carrying heavy things. - Jason Van Camp", "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy. - Martin Luther King, Jr.", "Don\'t let someone else\'s opinion of you become your reality. - Les Brown", "In life it\'s more important to ask questions than to provide answers. Questions are a true measure of a first rate mind. - John Villanueva"];

function quoteGen() {
  alert(leaderName + ": " + (quotes[Math.floor(Math.random()*quotes.length)]));
}

var leaderName = prompt("Hello. What is your name?");

function greeting() {
  alert("Welcome " + leaderName + " Your leadership journey starts now! Click on the Daily Leadership by Action button for your action today. Complete the action and come back tomorrow for another one.");
}


var dailyAct = ["Talk to one team player. Find out 4 things they do outside of work.", "Find out the names of your team mate\'s spouses and children.", "Memorize this quote: Show up. Even on your bad days. Those are sometimes the most important.", "Memorize these words from Maya Angelou: You may shoot me with your words, You may cut me with your eyes, You may kill me with your hatefulness, But still, like air, I\’\ll rise.", "Think of one person you work with that you do not like or get along with. Write down 3 things you like about this person. Focus on those 3 things when you see them today.", "You are who you hang out with. Call a great leader today and ask them how they learned to lead.", "Think of a great leader that you worked for in the past. Write down what made them great.", 
               "As a leader, you may be tempted to build relationships only with the people you like or with whom you are highly compatible, and to ignore the others. However, by doing that, you have the potential to lose a lot of people.  Today, remember that while the things we have in common may make relationships enjoyable, the differences are what really make them interesting.", "Connect with someone on your team. What three nonbusiness things do you know about this person?"];

function actionGen() {
  alert(leaderName + ", " + (dailyAct[Math.floor(Math.random()*dailyAct.length)] + "  Come back tomorrow for a new action to take."));
}
